# Generated by Django 4.0.5 on 2022-07-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_image_img_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoOptionPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('option_one', models.CharField(max_length=100)),
                ('option_two', models.CharField(max_length=100)),
            ],
        ),
    ]
