# Generated by Django 4.0.5 on 2022-07-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_twooptionpoll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twooptionpoll',
            old_name='title',
            new_name='question',
        ),
    ]
