# Generated by Django 4.0.5 on 2022-07-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_title_twooptionpoll_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='twooptionpoll',
            name='option_one_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twooptionpoll',
            name='option_two_count',
            field=models.IntegerField(default=0),
        ),
    ]
