# Generated by Django 4.0.5 on 2022-07-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_twooptionpoll_option_one_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twooptionpoll',
            name='option_one',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='twooptionpoll',
            name='option_two',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='twooptionpoll',
            name='question',
            field=models.TextField(max_length=100),
        ),
    ]
