# Generated by Django 4.0.5 on 2022-07-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_twooptionpoll_option_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
