# Generated by Django 4.0.5 on 2022-07-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_twooptionpoll_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='twooptionpoll',
            name='user_votes',
            field=models.TextField(null=True),
        ),
    ]
