# Generated by Django 4.0.5 on 2022-07-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_todolist_todolistitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoListItems',
            new_name='ToDoListItem',
        ),
    ]
