# Generated by Django 4.0.5 on 2022-07-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_rename_todolistitems_todolistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todolistitem',
            name='todolist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to='website.todolist'),
        ),
    ]
